# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20171202_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Дата'),
        ),
    ]
