# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 00:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(upload_to='admin')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('colors', models.CharField(choices=[('red', 'red'), ('blue', 'blue'), ('green', 'green'), ('darkblue', 'darkblue'), ('orange', 'orange'), ('gray', 'gray'), ('yellow', 'yellow')], max_length=50)),
                ('usage', models.CharField(choices=[('basket', 'basketball'), ('child', 'childhood'), ('tennis', 'tennis'), ('volleyball', 'volleyball'), ('sport', 'sport'), ('gym', 'gym')], max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.Item'),
        ),
    ]
