# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 17:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagemodel',
            options={'verbose_name': 'Картинка', 'verbose_name_plural': 'Картинки'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='landing.Item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='colors',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('red', 'красный'), ('blue', 'синий'), ('green', 'зеленый'), ('darkblue', 'темно-синий'), ('orange', 'оранжевый'), ('gray', 'серый'), ('yellow', 'желтый')], max_length=50, verbose_name='Цвета'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='item',
            name='usage',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('basket', 'баскетбол'), ('child', 'дет. площадки'), ('tennis', 'теннис'), ('volleyball', 'воллейбол'), ('sport', 'спорт'), ('gym', 'тренажерный зал')], max_length=50, verbose_name='Использование'),
        ),
    ]
