# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 22:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20171128_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Цвет')),
                ('hex', models.CharField(max_length=30, verbose_name='hex представление')),
            ],
        ),
        migrations.AlterModelOptions(
            name='imagemodel',
            options={'ordering': ['pk'], 'verbose_name': 'Картинка', 'verbose_name_plural': 'Картинки'},
        ),
        migrations.RemoveField(
            model_name='item',
            name='colors',
        ),
        migrations.AddField(
            model_name='color',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='landing.Item'),
        ),
    ]
