# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_auto_20171201_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='item',
        ),
        migrations.AddField(
            model_name='item',
            name='colors',
            field=models.ManyToManyField(to='landing.Color'),
        ),
    ]
