# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 16:46
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_auto_20171202_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='usage',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('basket', 'Покрытия для футбольных полей'), ('child', 'Покрытия для деских площадок'), ('tennis', 'Покрытия для теннисных площадок'), ('volleyball', 'Покрытия для воллейбольных площадок'), ('sprint', 'Покрытия для беговых дорожек'), ('footsteps', 'Покрытия для пешеходных дорожек'), ('football', 'Покрытия для футбольных полей'), ('stable', 'Напольные покрытия для конюшен')], max_length=50, verbose_name='Использование'),
        ),
    ]
