# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 16:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_auto_20171202_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagemodel',
            old_name='image',
            new_name='item',
        ),
        migrations.RemoveField(
            model_name='imagemodel',
            name='main_image',
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='big_image',
            field=models.ImageField(default=1, upload_to='admin', verbose_name='большая картинка внутри слайдера'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='little_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='admin', verbose_name='маленькая картинка для превью'),
            preserve_default=False,
        ),
    ]
