# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_auto_20171203_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title документа')),
                ('name', models.CharField(max_length=200, verbose_name='Название компании')),
                ('description', models.TextField(help_text='Короткое (500 символов) описание                                    сайта для улучшения взаимодействия с поисковыми движками', verbose_name='SEO description tag')),
                ('meta_keywords', models.TextField(help_text='Ключевые слова и поисковые фразы для                                      улучшения взаимодействия с поисковыми движками', verbose_name='SEO keywords')),
                ('country', models.CharField(max_length=80, verbose_name='Страна')),
                ('state', models.CharField(blank=True, help_text='Архангельская/Московская', max_length=80, verbose_name='Область')),
                ('street', models.CharField(max_length=150, verbose_name='Улица')),
                ('building', models.CharField(blank=True, max_length=50, verbose_name='Дом №')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Основная информация о компании',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Номер телефона')),
                ('main_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone', to='landing.MainInfo')),
            ],
            options={
                'verbose_name': 'Телефон',
                'verbose_name_plural': 'Телефоны',
            },
        ),
    ]
