# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0009_maininfo_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maininfo',
            options={'verbose_name': 'Основная информация о компании', 'verbose_name_plural': 'Основная информация о компании'},
        ),
        migrations.AddField(
            model_name='maininfo',
            name='city',
            field=models.CharField(blank=True, max_length=80, verbose_name='Город'),
        ),
    ]
