# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0011_maininfo_office'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='phone_number',
            new_name='number',
        ),
        migrations.AlterField(
            model_name='phone',
            name='main_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='landing.MainInfo'),
        ),
    ]
