# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 21:47
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0012_auto_20171203_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='item',
            field=models.ManyToManyField(blank=True, related_name='colors', to='landing.Item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='item',
            name='usage',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('basket', 'Покрытия для баскетбольных полей'), ('child', 'Покрытия для деских площадок'), ('tennis', 'Покрытия для теннисных площадок'), ('volleyball', 'Покрытия для воллейбольных площадок'), ('sprint', 'Покрытия для беговых дорожек'), ('footsteps', 'Покрытия для пешеходных дорожек'), ('football', 'Покрытия для футбольных полей'), ('stable', 'Напольные покрытия для конюшен')], max_length=300, verbose_name='Использование'),
        ),
    ]
